Initialize App_CI.yml : with @bassamEldsouki
DIT112-V21/group-07 pull request #29
Opened 2021-04-15 14:42 UTC by edizgenc2021

Subject: Initialize App CI
type: User Story
Problem: App CI
git tags: User story, Sprint1, High

Resolves user story #20

2021-04-15 14:52 UTC, bassamEldesouki commented
An App CI error because it can't find the directory we specified in the App_CI.yml file. This will be fixed after merging the App Android file to master.

2021-04-15 14:53 UTC, bassamEldesouki commented on .github/workflows/App_CI.yml
> +        cd app
Needs to be changed to the right directory!

2021-04-15 15:03 UTC, bassamEldesouki requested changes
It can't find the directory, Please write the right one!

2021-04-15 15:04 UTC, edizgenc2021 commented
> It can't find the directory, Please write the right one!

I see. I am aware : ) will do that very soon. Waiting for a colleague of mine to finish her pushes.

2021-04-16 11:33 UTC, edizgenc2021 commented on .github/workflows/App_CI.yml
> +        cd tree/UI/UI/app
The directory for the app has been changed.

2021-04-16 11:51 UTC, platisd commented
Read [how to create a commit with multiple authors](https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors). No need to tag like that on the pull request title (it doesn't provide more visibility)

2021-04-16 12:00 UTC, ediz-genc commented on .github/workflows/App_CI.yml
> +        cd UI
"Cd UI" added

2021-04-16 13:05 UTC, bassamEldesouki approved these changes
Fixed error  " can't find the directory of gradlew"

2021-04-16 16:01 UTC, bassamEldesouki approved these changes
It could be a solution!

2021-04-17 12:21 UTC, bassamEldesouki commented
This issue has been fixed with issue #38

2021-04-17 12:21 UTC, closed without merging